### ISSUE TITLE
Hitting Rate Limit for "Export App Sign On Policies (experimental)"

### ISSUE THREAD

**Issue by trackoverxc** [gabrielsroka/gabrielsroka.github.io#14]
Hello, when I use the "Export App Sign On Policies (Experimental)" the requests seem to hit a rate limit. I don't see the number of requests totaling any of the limits mentioned in https://developer.okta.com/docs/reference/rate-limits/ though. It seems to start throttling around 120 requests.

**Comment by gabrielsroka** [comment]
Hi @trackoverxc 

That's a known issue. That's why it's called 'experimental'. That particular feature doesn't work with rate limits (but most of the rest of rockstar does). If you happen to have a small enough number of policies, it will work. If not, you'll get rate limit errors.

My recommendation is to use another script, eg in Python or PowerShell. I have some examples to get your started.

Thanks.

**Comment by trackoverxc** [comment]
The examples would be much appreciated. I've been trying in Python but can't get past the authentication portion.

**Comment by gabrielsroka** [comment]
this Python code does the auth for the private APIs, but not the rest (but it could...)
https://github.com/gabrielsroka/okta_api/blob/master/okta_auth.py

This PowerShell does the auth and calls the private APIs:
https://github.com/gabrielsroka/OktaAPI.psm1/blob/master/OktaPrivateAPI.ps1#L54-L55

**Comment by gabrielsroka** [comment]
hi @trackoverxc 

does this help? i'm going to close this for now. If you have more questions, please reopen it.

**Comment by trackoverxc** [comment]
We ended up not needing the data so I didn't try the workaround, but thank
you.
