### ISSUE TITLE
Okta.pq - Pagination does not work

### ISSUE THREAD

**Issue by campmd** [gabrielsroka/gabrielsroka.github.io#64]
Trying to get Okta logs or Okta users does not allow going beyond the 1000 logs or 200 users. Did the pagination work before?
The queries I am doing should return over 10000 logs or 4500 users.

**Comment by gabrielsroka** [comment]
i wrote that 5 yrs ago and haven't used it since.

at the time, there was a limitation that a regular .pq file couldn't see the response headers that are necessary to paginate. there was a workaround in the file.

perhaps that limitation no longer exists.

either way, i'm not supporting that file anymore.

good luck.

**Comment by gabrielsroka** [comment]
i also posted some answers on MSFT's forum.
